WITH RECURSIVE ECOLI_TREE AS (
SELECT A.ID,1 AS GEN
FROM ECOLI_DATA A
WHERE A.PARENT_ID IS NULL
UNION ALL
SELECT B.ID, T.GEN+1
FROM ECOLI_DATA B
JOIN ECOLI_TREE T ON T.ID=B.PARENT_ID)
SELECT T.ID
FROM ECOLI_TREE T
WHERE T.GEN=3
ORDER BY T.ID;