SELECT DATE_FORMAT(F.SALES_DATE,'%Y-%m-%d') AS SALES_DATE,F.PRODUCT_ID,F.USER_ID,F.SALES_AMOUNT
FROM (
SELECT SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'
UNION ALL
SELECT SALES_DATE,PRODUCT_ID,NULL AS USER_ID,SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%') AS F
ORDER BY SALES_DATE,PRODUCT_ID,USER_ID