WITH AVAILABLE_CAR AS (
    SELECT A.CAR_ID,A.CAR_TYPE,A.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    WHERE NOT EXISTS(SELECT 1
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
                    WHERE A.CAR_ID=B.CAR_ID AND (B.START_DATE<='2022-11-30' AND B.END_DATE>='2022-11-01')) AND
                    A.CAR_TYPE IN ('세단','SUV'))
SELECT C.CAR_ID,C.CAR_TYPE,TRUNCATE((100-D.DISCOUNT_RATE)*C.DAILY_FEE*30/100,0) AS FEE
FROM AVAILABLE_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON (D.DURATION_TYPE='30일 이상' AND D.CAR_TYPE=C.CAR_TYPE)
HAVING FEE BETWEEN 500000 AND 2000000-1
ORDER BY 3 DESC,2 ASC, 1 DESC;
    