-- 코드를 입력하세요
WITH CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS (SELECT CAR_TYPE, DISCOUNT_RATE
                                         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                                         WHERE DURATION_TYPE='30일 이상' AND CAR_TYPE IN ('세단','SUV')),
     CAR_RENTAL_COMPANY_CAR AS (SELECT CAR_ID,CAR_TYPE,DAILY_FEE
                               FROM CAR_RENTAL_COMPANY_CAR 
                               WHERE CAR_TYPE IN ('세단','SUV'))
SELECT A.CAR_ID,A.CAR_TYPE, TRUNCATE(A.DAILY_FEE*(100-B.DISCOUNT_RATE)*30/100,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE=B.CAR_TYPE
WHERE NOT EXISTS (SELECT 1
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C 
                 WHERE A.CAR_ID=C.CAR_ID AND (START_DATE<='2022-11-30' AND END_DATE>='2022-11-01')) 
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC,A.CAR_TYPE , A.CAR_ID DESC;
