-- 코드를 입력하세요
SELECT T.FOOD_TYPE,T.REST_ID,T.REST_NAME,T.FAVORITES
FROM (SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES, RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK
     FROM REST_INFO) AS T
WHERE RNK=1
ORDER BY T.FOOD_TYPE DESC;