-- 년도 별로 회원가입한 사람 수와, 년도,달 별로 당해 가입했는데 해당 달에 구매한 사람들 구매 데이터를 구함.  
WITH ANNUAL_SIGNED_UP AS (SELECT YEAR(A.JOINED) AS YEAR, COUNT(A.USER_ID) AS SIGNED_UP_USERS
                FROM USER_INFO A
                WHERE YEAR(A.JOINED)=2021
                GROUP BY YEAR(A.JOINED)),
    MONTHLY_PURCHASED AS (SELECT YEAR(A.SALES_DATE) AS YEAR,MONTH(A.SALES_DATE) AS MONTH, COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS
                FROM ONLINE_SALE A
                JOIN USER_INFO B ON A.USER_ID=B.USER_ID
                WHERE YEAR(B.JOINED)=2021
                GROUP BY YEAR(A.SALES_DATE),MONTH(A.SALES_DATE))
SELECT A.YEAR, A.MONTH, A.PURCHASED_USERS, ROUND((A.PURCHASED_USERS/B.SIGNED_UP_USERS),1) AS PURCHASED_RATIO
FROM MONTHLY_PURCHASED A,ANNUAL_SIGNED_UP B
GROUP BY A.YEAR,A.MONTH;