WITH TOTAL_NUM AS (SELECT COUNT(USER_ID) AS TOTAL FROM USER_INFO WHERE YEAR(JOINED)=2021 )
SELECT YEAR(A.SALES_DATE) AS YEAR,MONTH(A.SALES_DATE) AS MONTH,
        COUNT(DISTINCT A.USER_ID) AS PUSCHASED_USERS,
        ROUND(COUNT(DISTINCT A.USER_ID)/B.TOTAL,1) AS PURCHASED_RATIO
FROM ONLINE_SALE A
JOIN TOTAL_NUM B
JOIN USER_INFO C ON A.USER_ID=C.USER_ID
WHERE YEAR(C.JOINED)=2021
GROUP BY YEAR(A.SALES_DATE),MONTH(A.SALES_DATE)
