SET @TOTAL_NUMBER=(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021);
SELECT 
YEAR(A.SALES_DATE) AS YEAR,
MONTH(A.SALES_DATE) AS MONTH,
COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT A.USER_ID)/@TOTAL_NUMBER,1) AS PURCHASED_RATIO 
FROM ONLINE_SALE A
JOIN USER_INFO B ON A.USER_ID=B.USER_ID
WHERE YEAR(B.JOINED)=2021
GROUP BY YEAR(A.SALES_DATE),MONTH(A.SALES_DATE)
ORDER BY 1,2;