WITH RECURSIVE ECOLI_TREE AS (
SELECT ID, PARENT_ID, 1 AS GEN 
    -- 1세대 친구들 테이블로 만듦
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL
UNION ALL
SELECT A.ID, A.PARENT_ID, T.GEN+1 AS GEN
FROM ECOLI_DATA A
JOIN ECOLI_TREE T ON T.ID=A.PARENT_ID
) 
SELECT COUNT(T.ID) AS COUNT,T.GEN AS GENERATION
FROM ECOLI_TREE T
WHERE NOT EXISTS (SELECT 1
                 FROM ECOLI_DATA B
                 WHERE T.ID=B.PARENT_ID)
GROUP BY T.GEN
ORDER BY T.GEN;