WITH RECURSIVE GENMAP AS (
            SELECT
            1 AS GENERATION,
            A.ID,
            B.ID AS CHILD_ID
            FROM ECOLI_DATA A
            LEFT JOIN ECOLI_DATA B ON A.ID=B.PARENT_ID
            WHERE A.PARENT_ID IS NULL
    
            UNION ALL
    
            SELECT
            G.GENERATION+1 AS GENERATION,
            G.CHILD_ID AS ID,
            C.ID AS CHILD_ID
            FROM GENMAP G
            LEFT JOIN ECOLI_DATA C ON G.CHILD_ID=C.PARENT_ID
            WHERE G.CHILD_ID IS NOT NULL)
SELECT COUNT(*) AS "COUNT", GENERATION
FROM GENMAP
WHERE CHILD_ID IS NULL
GROUP BY GENERATION
ORDER BY 2;
