-- 코드를 입력하세요
SELECT A.CAR_ID, MAX(CASE WHEN '2022-10-16' BETWEEN A.START_DATE AND A.END_DATE THEN '대여중'
                ELSE '대여 가능'
                END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC;