-- 코드를 입력하세요
WITH HEAVYUSER AS (SELECT B.HOST_ID
              FROM PLACES B
              GROUP BY B.HOST_ID
              HAVING COUNT(HOST_ID)>=2)
SELECT A.ID,A.NAME,A.HOST_ID
FROM PLACES A
WHERE A.HOST_ID IN (SELECT *
                   FROM HEAVYUSER)
ORDER BY A.ID