-- 코드를 입력하세요
WITH CAR_RENTAL_COMPANY_RENTAL_HISTORY AS (
SELECT HISTORY_ID,CAR_ID,START_DATE,END_DATE, CASE WHEN DATEDIFF(END_DATE,START_DATE)+1>=90 THEN '90일 이상'
                                                WHEN DATEDIFF(END_DATE,START_DATE)+1>=30 THEN '30일 이상'
                                                WHEN DATEDIFF(END_DATE,START_DATE)+1>=7 THEN '7일 이상'
                                                END AS DURATION_TYPE,DATEDIFF(END_DATE,START_DATE)+1 AS DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)
SELECT B.HISTORY_ID,TRUNCATE((1-COALESCE(C.DISCOUNT_RATE,0)/100)*A.DAILY_FEE*B.DURATION,0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
JOIN CAR_RENTAL_COMPANY_CAR A ON B.CAR_ID=A.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON (A.CAR_TYPE,B.DURATION_TYPE)=(C.CAR_TYPE,C.DURATION_TYPE)
WHERE A.CAR_TYPE='트럭'
ORDER BY FEE DESC,HISTORY_ID DESC;