-- 코드를 입력하세요
WITH JULY AS (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
             FROM JULY
             GROUP BY FLAVOR)
SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN JULY B ON A.FLAVOR=B.FLAVOR
ORDER BY A.TOTAL_ORDER+B.TOTAL_ORDER DESC
LIMIT 3;