-- 코드를 입력하세요
SELECT C.APNT_NO,A.PT_NAME,C.PT_NO,C.MCDP_CD,B.DR_NAME,C.APNT_YMD
FROM APPOINTMENT C
JOIN PATIENT A ON C.PT_NO=A.PT_NO
JOIN DOCTOR B ON C.MDDR_ID=B.DR_ID
WHERE C.APNT_CNCL_YN='N' AND APNT_YMD LIKE '2022-04-13%' AND C.MCDP_CD='CS'
ORDER BY C.APNT_YMD;