-- 코드를 입력하세요
WITH RECURSIVE TIMETABLE AS (
SELECT 0 AS HOUR
UNION ALL
SELECT T.HOUR+1
FROM TIMETABLE T
WHERE HOUR<23 )
SELECT T.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM TIMETABLE T
LEFT JOIN ANIMAL_OUTS A ON T.HOUR=HOUR(A.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;