-- 코드를 작성해주세요
SELECT A.ID,A.EMAIL,A.FIRST_NAME,A.LAST_NAME
FROM DEVELOPERS A
WHERE EXISTS (SELECT 1
             FROM SKILLCODES B
             WHERE A.SKILL_CODE & B.CODE AND B.CATEGORY LIKE 'Front End')
ORDER BY ID;