-- 코드를 입력하세요
SELECT T.USER_ID, T.NICKNAME, T.TOTAL_SALES
FROM (SELECT U.USER_ID,U.NICKNAME,SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U ON B.WRITER_ID=U.USER_ID
WHERE B.STATUS='DONE'
GROUP BY U.USER_ID) AS T
WHERE T.TOTAL_SALES>=700000
ORDER BY TOTAL_SALES