WITH REVIEW_RNK AS (
    SELECT MEMBER_ID,RANK() OVER(ORDER BY COUNT(REVIEW_ID) DESC) AS RNK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID)
SELECT A.MEMBER_NAME,C.REVIEW_TEXT,DATE_FORMAT(C.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN REVIEW_RNK B ON A.MEMBER_ID=B.MEMBER_ID
JOIN REST_REVIEW C ON A.MEMBER_ID=C.MEMBER_ID
WHERE B.RNK=1
ORDER BY 3,2; 