-- 코드를 입력하세요
WITH TOTAL_REVIEW AS (SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEWNUM
                     FROM REST_REVIEW
                     GROUP BY MEMBER_ID)
SELECT A.MEMBER_NAME,B.REVIEW_TEXT,DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B ON A.MEMBER_ID=B.MEMBER_ID
JOIN TOTAL_REVIEW C ON A.MEMBER_ID=C.MEMBER_ID
WHERE C.REVIEWNUM IN (SELECT MAX(REVIEWNUM)
                     FROM TOTAL_REVIEW 
                     )
ORDER BY REVIEW_DATE,REVIEW_TEXT