SELECT A.ITEM_ID,B.ITEM_NAME,B.RARITY
FROM (SELECT T.ITEM_ID 
     FROM ITEM_INFO I
     JOIN ITEM_TREE T ON I.ITEM_ID=T.PARENT_ITEM_ID
     WHERE I.RARITY='RARE') AS A
JOIN ITEM_INFO AS B ON A.ITEM_ID=B.ITEM_ID
ORDER BY A.ITEM_ID DESC;