-- 코드를 작성해주세요
SELECT ITEM_ID,ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID IN (
    SELECT T.ITEM_ID 
    FROM ITEM_TREE AS T 
    JOIN ITEM_INFO AS I ON I.ITEM_ID=T.PARENT_ITEM_ID
    WHERE I.RARITY ='RARE'
    )
ORDER BY ITEM_ID DESC;

