WITH TARGET AS (SELECT CAR_ID, COUNT(HISTORY_ID) AS COUNTS
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
               WHERE YEAR(START_DATE)=2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
               GROUP BY CAR_ID)
SELECT MONTH(A.START_DATE) AS MONTH, T.CAR_ID, COUNT(A.HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN TARGET T ON A.CAR_ID=T.CAR_ID
WHERE T.COUNTS>=5 AND (YEAR(START_DATE)=2022 AND MONTH(START_DATE) BETWEEN 8 AND 10)
GROUP BY MONTH(A.START_DATE),T.CAR_ID
ORDER BY MONTH(A.START_DATE), T.CAR_ID DESC;