SELECT YEAR(B.DIFFERENTIATION_DATE) AS YEAR, T.MAXSIZE-B.SIZE_OF_COLONY AS YEAR_DEV, B.ID
FROM ECOLI_DATA B
LEFT JOIN (SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR,MAX(SIZE_OF_COLONY) AS MAXSIZE
     FROM ECOLI_DATA A
     GROUP BY YEAR(A.DIFFERENTIATION_DATE)) AS T
ON YEAR(B.DIFFERENTIATION_DATE)=T.YEAR
ORDER BY T.YEAR, YEAR_DEV;

