WITH MAXPERYEAR AS (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXSIZE
                   FROM ECOLI_DATA
                   GROUP BY YEAR(DIFFERENTIATION_DATE))
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, M.MAXSIZE-A.SIZE_OF_COLONY AS YEAR_DEV,A.ID
FROM ECOLI_DATA A
JOIN MAXPERYEAR M ON YEAR(A.DIFFERENTIATION_DATE)=M.YEAR
ORDER BY YEAR,YEAR_DEV;