SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO I
WHERE EXISTS(SELECT 1
            FROM FISH_NAME_INFO N
            WHERE N.FISH_NAME IN ('BASS','SNAPPER')
            AND I.FISH_TYPE=N.FISH_TYPE) ;
        