WITH SUMSCORE AS (SELECT EMP_NO,  SUM(SCORE) AS S
                 FROM HR_GRADE
                 GROUP BY EMP_NO)
SELECT B.S AS SCORE,A.EMP_NO,A.EMP_NAME,A.POSITION,A.EMAIL
FROM HR_EMPLOYEES A
JOIN SUMSCORE B ON A.EMP_NO=B.EMP_NO
WHERE B.S=(SELECT MAX(S)
          FROM SUMSCORE);