-- 코드를 입력하세요
SELECT A.CATEGORY,A.PRICE AS MAX_PRICE ,A.PRODUCT_NAME
FROM (SELECT B.CATEGORY, MAX(B.PRICE) AS PRICE
     FROM FOOD_PRODUCT B
     WHERE B.CATEGORY IN ('과자', '국', '김치', '식용유')
     GROUP BY B.CATEGORY) AS C
JOIN FOOD_PRODUCT A ON A.CATEGORY=C.CATEGORY AND A.PRICE=C.PRICE
ORDER BY A.PRICE DESC;