WITH DEVELOPER_GRADE AS (
SELECT CASE WHEN (SUM(CASE WHEN B.NAME='PYTHON' THEN 1 ELSE 0 END) >0
                               AND SUM(CASE WHEN B.CATEGORY='Front End' THEN 1 ELSE 0 END)>0) THEN 'A'
                    WHEN (SUM(CASE WHEN B.NAME='C#' THEN 1 ELSE 0 END)>0) THEN 'B'
                    WHEN (SUM(CASE WHEN B.CATEGORY='Front End' THEN 1 ELSE 0 END)>0) THEN 'C'
                    END AS GRADE,
                    A.ID,A.EMAIL
FROM DEVELOPERS A
JOIN SKILLCODES B ON A.SKILL_CODE & B.CODE = B.CODE
GROUP BY A.ID,A.EMAIL
)
SELECT GRADE,ID,EMAIL
FROM DEVELOPER_GRADE
WHERE GRADE IS NOT NULL
ORDER BY 1,2;