WITH DEVELOPERS_SKILLS AS (SELECT A.ID,A.EMAIL,B.NAME AS SKILL_NAME, B.CATEGORY AS SKILL_CATEGORY
                            FROM DEVELOPERS A
                            JOIN SKILLCODES B ON A.SKILL_CODE & B.CODE > 0),
    GRADES AS (SELECT CASE WHEN 'Front End' IN (SELECT D.SKILL_CATEGORY FROM DEVELOPERS_SKILLS D WHERE D.ID=C.ID) AND 'Python' IN (SELECT D.SKILL_NAME FROM DEVELOPERS_SKILLS D WHERE D.ID=C.ID) THEN 'A'
    WHEN 'C#' IN (SELECT D.SKILL_NAME FROM DEVELOPERS_SKILLS D WHERE D.ID=C.ID) THEN 'B'
    WHEN 'Front End' IN (SELECT D.SKILL_CATEGORY FROM DEVELOPERS_SKILLS D WHERE D.ID=C.ID) THEN 'C'
    END AS GRADE,
    C.ID, C.EMAIL
    FROM DEVELOPERS_SKILLS C)
SELECT DISTINCT GRADE,ID,EMAIL
FROM GRADES
WHERE GRADE IS NOT NULL
ORDER BY GRADE,ID;